### ISSUE TITLE
Getting fields by column names

### ISSUE THREAD

**Issue by fertkir** [jamel/dbf#16]
Hi,

Would be good to have ResultSet-like API for DbfReader with ability to get fields by column names, e.g.

```
DbfRow row;
while ((row = reader.nextDbfRow()) != null) {
    totalSum += row.getDouble("BalanceUSD");
}
```

**Comment by fertkir** [comment]
I could implement it and make a pull request. What would you say?

**Comment by jamel** [comment]
@fertkir It will be perfect!

**Comment by fertkir** [comment]
@jamel OK

**Comment by fertkir** [comment]
@jamel,
1. Do I understand it correctly that the library must be Java 6 compatible?
2. May I use Mockito 1.10 for unit tests?

**Comment by jamel** [comment]
1. Yes, you're right. The main reason for this is legacy projects which are using this library and which are not trivial to upgrade.
2. Personally I don't like to have much dependencies. But if it will be used only for tests - it's ok.
